//go:build !ignore_autogenerated

/*
Copyright 2026 NVIDIA

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BFBRegistryConfiguration) DeepCopyInto(out *BFBRegistryConfiguration) {
	*out = *in
	if in.Disable != nil {
		in, out := &in.Disable, &out.Disable
		*out = new(bool)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BFBRegistryConfiguration.
func (in *BFBRegistryConfiguration) DeepCopy() *BFBRegistryConfiguration {
	if in == nil {
		return nil
	}
	out := new(BFBRegistryConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaseComponentConfig) DeepCopyInto(out *BaseComponentConfig) {
	*out = *in
	if in.Disable != nil {
		in, out := &in.Disable, &out.Disable
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaseComponentConfig.
func (in *BaseComponentConfig) DeepCopy() *BaseComponentConfig {
	if in == nil {
		return nil
	}
	out := new(BaseComponentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaseControllerConfig) DeepCopyInto(out *BaseControllerConfig) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaseControllerConfig.
func (in *BaseControllerConfig) DeepCopy() *BaseControllerConfig {
	if in == nil {
		return nil
	}
	out := new(BaseControllerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNIInstallerConfiguration) DeepCopyInto(out *CNIInstallerConfiguration) {
	*out = *in
	in.BaseComponentConfig.DeepCopyInto(&out.BaseComponentConfig)
	in.HelmComponentConfig.DeepCopyInto(&out.HelmComponentConfig)
	if in.Installer != nil {
		in, out := &in.Installer, &out.Installer
		*out = new(DefaultOverridesConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNIInstallerConfiguration.
func (in *CNIInstallerConfiguration) DeepCopy() *CNIInstallerConfiguration {
	if in == nil {
		return nil
	}
	out := new(CNIInstallerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPFOperatorConfig) DeepCopyInto(out *DPFOperatorConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPFOperatorConfig.
func (in *DPFOperatorConfig) DeepCopy() *DPFOperatorConfig {
	if in == nil {
		return nil
	}
	out := new(DPFOperatorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DPFOperatorConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPFOperatorConfigList) DeepCopyInto(out *DPFOperatorConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DPFOperatorConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPFOperatorConfigList.
func (in *DPFOperatorConfigList) DeepCopy() *DPFOperatorConfigList {
	if in == nil {
		return nil
	}
	out := new(DPFOperatorConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DPFOperatorConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPFOperatorConfigSpec) DeepCopyInto(out *DPFOperatorConfigSpec) {
	*out = *in
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = new(Overrides)
		(*in).DeepCopyInto(*out)
	}
	if in.Networking != nil {
		in, out := &in.Networking, &out.Networking
		*out = new(Networking)
		(*in).DeepCopyInto(*out)
	}
	if in.Monitoring != nil {
		in, out := &in.Monitoring, &out.Monitoring
		*out = new(MonitoringConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DPUServiceController != nil {
		in, out := &in.DPUServiceController, &out.DPUServiceController
		*out = new(DPUServiceControllerConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.ProvisioningController != nil {
		in, out := &in.ProvisioningController, &out.ProvisioningController
		*out = new(ProvisioningControllerConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceSetController != nil {
		in, out := &in.ServiceSetController, &out.ServiceSetController
		*out = new(ServiceSetControllerConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.DPUDetector != nil {
		in, out := &in.DPUDetector, &out.DPUDetector
		*out = new(DPUDetectorConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Multus != nil {
		in, out := &in.Multus, &out.Multus
		*out = new(MultusConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.SRIOVDevicePlugin != nil {
		in, out := &in.SRIOVDevicePlugin, &out.SRIOVDevicePlugin
		*out = new(SRIOVDevicePluginConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Flannel != nil {
		in, out := &in.Flannel, &out.Flannel
		*out = new(FlannelConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.OVSCNI != nil {
		in, out := &in.OVSCNI, &out.OVSCNI
		*out = new(OVSCNIConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.NVIPAM != nil {
		in, out := &in.NVIPAM, &out.NVIPAM
		*out = new(NVIPAMConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.CNIInstaller != nil {
		in, out := &in.CNIInstaller, &out.CNIInstaller
		*out = new(CNIInstallerConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.SFCController != nil {
		in, out := &in.SFCController, &out.SFCController
		*out = new(SFCControllerConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.KamajiClusterManager != nil {
		in, out := &in.KamajiClusterManager, &out.KamajiClusterManager
		*out = new(KamajiClusterManagerConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.StaticClusterManager != nil {
		in, out := &in.StaticClusterManager, &out.StaticClusterManager
		*out = new(StaticClusterManagerConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSRIOVDevicePluginController != nil {
		in, out := &in.NodeSRIOVDevicePluginController, &out.NodeSRIOVDevicePluginController
		*out = new(NodeSRIOVDevicePluginControllerConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPFOperatorConfigSpec.
func (in *DPFOperatorConfigSpec) DeepCopy() *DPFOperatorConfigSpec {
	if in == nil {
		return nil
	}
	out := new(DPFOperatorConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPFOperatorConfigStatus) DeepCopyInto(out *DPFOperatorConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPFOperatorConfigStatus.
func (in *DPFOperatorConfigStatus) DeepCopy() *DPFOperatorConfigStatus {
	if in == nil {
		return nil
	}
	out := new(DPFOperatorConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPUDetectorConfiguration) DeepCopyInto(out *DPUDetectorConfiguration) {
	*out = *in
	in.BaseComponentConfig.DeepCopyInto(&out.BaseComponentConfig)
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.Daemon != nil {
		in, out := &in.Daemon, &out.Daemon
		*out = new(DefaultOverridesConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPUDetectorConfiguration.
func (in *DPUDetectorConfiguration) DeepCopy() *DPUDetectorConfiguration {
	if in == nil {
		return nil
	}
	out := new(DPUDetectorConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DPUServiceControllerConfiguration) DeepCopyInto(out *DPUServiceControllerConfiguration) {
	*out = *in
	in.BaseComponentConfig.DeepCopyInto(&out.BaseComponentConfig)
	in.BaseControllerConfig.DeepCopyInto(&out.BaseControllerConfig)
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.Controller != nil {
		in, out := &in.Controller, &out.Controller
		*out = new(DefaultOverridesConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.DisableDPUReadyTaints != nil {
		in, out := &in.DisableDPUReadyTaints, &out.DisableDPUReadyTaints
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DPUServiceControllerConfiguration.
func (in *DPUServiceControllerConfiguration) DeepCopy() *DPUServiceControllerConfiguration {
	if in == nil {
		return nil
	}
	out := new(DPUServiceControllerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultOverridesConfiguration) DeepCopyInto(out *DefaultOverridesConfiguration) {
	*out = *in
	in.ImageComponentConfig.DeepCopyInto(&out.ImageComponentConfig)
	in.ResourceComponentConfig.DeepCopyInto(&out.ResourceComponentConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultOverridesConfiguration.
func (in *DefaultOverridesConfiguration) DeepCopy() *DefaultOverridesConfiguration {
	if in == nil {
		return nil
	}
	out := new(DefaultOverridesConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlannelCNI) DeepCopyInto(out *FlannelCNI) {
	*out = *in
	in.ImageComponentConfig.DeepCopyInto(&out.ImageComponentConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlannelCNI.
func (in *FlannelCNI) DeepCopy() *FlannelCNI {
	if in == nil {
		return nil
	}
	out := new(FlannelCNI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlannelConfiguration) DeepCopyInto(out *FlannelConfiguration) {
	*out = *in
	in.BaseComponentConfig.DeepCopyInto(&out.BaseComponentConfig)
	in.HelmComponentConfig.DeepCopyInto(&out.HelmComponentConfig)
	if in.CNI != nil {
		in, out := &in.CNI, &out.CNI
		*out = new(FlannelCNI)
		(*in).DeepCopyInto(*out)
	}
	if in.Daemon != nil {
		in, out := &in.Daemon, &out.Daemon
		*out = new(FlannelDaemon)
		(*in).DeepCopyInto(*out)
	}
	if in.Images != nil {
		in, out := &in.Images, &out.Images
		*out = new(FlannelImages)
		**out = **in
	}
	if in.PodCIDR != nil {
		in, out := &in.PodCIDR, &out.PodCIDR
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlannelConfiguration.
func (in *FlannelConfiguration) DeepCopy() *FlannelConfiguration {
	if in == nil {
		return nil
	}
	out := new(FlannelConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlannelDaemon) DeepCopyInto(out *FlannelDaemon) {
	*out = *in
	in.ImageComponentConfig.DeepCopyInto(&out.ImageComponentConfig)
	in.ResourceComponentConfig.DeepCopyInto(&out.ResourceComponentConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlannelDaemon.
func (in *FlannelDaemon) DeepCopy() *FlannelDaemon {
	if in == nil {
		return nil
	}
	out := new(FlannelDaemon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlannelImages) DeepCopyInto(out *FlannelImages) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlannelImages.
func (in *FlannelImages) DeepCopy() *FlannelImages {
	if in == nil {
		return nil
	}
	out := new(FlannelImages)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmComponentConfig) DeepCopyInto(out *HelmComponentConfig) {
	*out = *in
	if in.HelmChart != nil {
		in, out := &in.HelmChart, &out.HelmChart
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmComponentConfig.
func (in *HelmComponentConfig) DeepCopy() *HelmComponentConfig {
	if in == nil {
		return nil
	}
	out := new(HelmComponentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageComponentConfig) DeepCopyInto(out *ImageComponentConfig) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageComponentConfig.
func (in *ImageComponentConfig) DeepCopy() *ImageComponentConfig {
	if in == nil {
		return nil
	}
	out := new(ImageComponentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallViaGNOI) DeepCopyInto(out *InstallViaGNOI) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallViaGNOI.
func (in *InstallViaGNOI) DeepCopy() *InstallViaGNOI {
	if in == nil {
		return nil
	}
	out := new(InstallViaGNOI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallViaHostAgent) DeepCopyInto(out *InstallViaHostAgent) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallViaHostAgent.
func (in *InstallViaHostAgent) DeepCopy() *InstallViaHostAgent {
	if in == nil {
		return nil
	}
	out := new(InstallViaHostAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallViaRedfish) DeepCopyInto(out *InstallViaRedfish) {
	*out = *in
	if in.BFBRegistry != nil {
		in, out := &in.BFBRegistry, &out.BFBRegistry
		*out = new(BFBRegistryConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.SkipDPUNodeDiscovery != nil {
		in, out := &in.SkipDPUNodeDiscovery, &out.SkipDPUNodeDiscovery
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallViaRedfish.
func (in *InstallViaRedfish) DeepCopy() *InstallViaRedfish {
	if in == nil {
		return nil
	}
	out := new(InstallViaRedfish)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KamajiClusterManagerConfiguration) DeepCopyInto(out *KamajiClusterManagerConfiguration) {
	*out = *in
	in.BaseComponentConfig.DeepCopyInto(&out.BaseComponentConfig)
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.Controller != nil {
		in, out := &in.Controller, &out.Controller
		*out = new(DefaultOverridesConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KamajiClusterManagerConfiguration.
func (in *KamajiClusterManagerConfiguration) DeepCopy() *KamajiClusterManagerConfiguration {
	if in == nil {
		return nil
	}
	out := new(KamajiClusterManagerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeStateMetricsConfiguration) DeepCopyInto(out *KubeStateMetricsConfiguration) {
	*out = *in
	in.BaseComponentConfig.DeepCopyInto(&out.BaseComponentConfig)
	in.HelmComponentConfig.DeepCopyInto(&out.HelmComponentConfig)
	if in.Daemon != nil {
		in, out := &in.Daemon, &out.Daemon
		*out = new(DefaultOverridesConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeStateMetricsConfiguration.
func (in *KubeStateMetricsConfiguration) DeepCopy() *KubeStateMetricsConfiguration {
	if in == nil {
		return nil
	}
	out := new(KubeStateMetricsConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringConfiguration) DeepCopyInto(out *MonitoringConfiguration) {
	*out = *in
	if in.Disable != nil {
		in, out := &in.Disable, &out.Disable
		*out = new(bool)
		**out = **in
	}
	if in.KubeStateMetrics != nil {
		in, out := &in.KubeStateMetrics, &out.KubeStateMetrics
		*out = new(KubeStateMetricsConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeProblemDetector != nil {
		in, out := &in.NodeProblemDetector, &out.NodeProblemDetector
		*out = new(NodeProblemDetectorConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.OpenTelemetryCollector != nil {
		in, out := &in.OpenTelemetryCollector, &out.OpenTelemetryCollector
		*out = new(OpenTelemetryCollectorConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringConfiguration.
func (in *MonitoringConfiguration) DeepCopy() *MonitoringConfiguration {
	if in == nil {
		return nil
	}
	out := new(MonitoringConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultusConfiguration) DeepCopyInto(out *MultusConfiguration) {
	*out = *in
	in.BaseComponentConfig.DeepCopyInto(&out.BaseComponentConfig)
	in.HelmComponentConfig.DeepCopyInto(&out.HelmComponentConfig)
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.CNI != nil {
		in, out := &in.CNI, &out.CNI
		*out = new(DefaultOverridesConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultusConfiguration.
func (in *MultusConfiguration) DeepCopy() *MultusConfiguration {
	if in == nil {
		return nil
	}
	out := new(MultusConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NVIPAMConfiguration) DeepCopyInto(out *NVIPAMConfiguration) {
	*out = *in
	in.BaseComponentConfig.DeepCopyInto(&out.BaseComponentConfig)
	in.HelmComponentConfig.DeepCopyInto(&out.HelmComponentConfig)
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.Controller != nil {
		in, out := &in.Controller, &out.Controller
		*out = new(NVIPAMController)
		(*in).DeepCopyInto(*out)
	}
	if in.Node != nil {
		in, out := &in.Node, &out.Node
		*out = new(NVIPAMNode)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NVIPAMConfiguration.
func (in *NVIPAMConfiguration) DeepCopy() *NVIPAMConfiguration {
	if in == nil {
		return nil
	}
	out := new(NVIPAMConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NVIPAMController) DeepCopyInto(out *NVIPAMController) {
	*out = *in
	in.ImageComponentConfig.DeepCopyInto(&out.ImageComponentConfig)
	in.ResourceComponentConfig.DeepCopyInto(&out.ResourceComponentConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NVIPAMController.
func (in *NVIPAMController) DeepCopy() *NVIPAMController {
	if in == nil {
		return nil
	}
	out := new(NVIPAMController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NVIPAMNode) DeepCopyInto(out *NVIPAMNode) {
	*out = *in
	in.ImageComponentConfig.DeepCopyInto(&out.ImageComponentConfig)
	in.ResourceComponentConfig.DeepCopyInto(&out.ResourceComponentConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NVIPAMNode.
func (in *NVIPAMNode) DeepCopy() *NVIPAMNode {
	if in == nil {
		return nil
	}
	out := new(NVIPAMNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Networking) DeepCopyInto(out *Networking) {
	*out = *in
	if in.ControlPlaneMTU != nil {
		in, out := &in.ControlPlaneMTU, &out.ControlPlaneMTU
		*out = new(int)
		**out = **in
	}
	if in.HighSpeedMTU != nil {
		in, out := &in.HighSpeedMTU, &out.HighSpeedMTU
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Networking.
func (in *Networking) DeepCopy() *Networking {
	if in == nil {
		return nil
	}
	out := new(Networking)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeProblemDetectorConfiguration) DeepCopyInto(out *NodeProblemDetectorConfiguration) {
	*out = *in
	in.BaseComponentConfig.DeepCopyInto(&out.BaseComponentConfig)
	in.HelmComponentConfig.DeepCopyInto(&out.HelmComponentConfig)
	if in.Daemon != nil {
		in, out := &in.Daemon, &out.Daemon
		*out = new(DefaultOverridesConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeProblemDetectorConfiguration.
func (in *NodeProblemDetectorConfiguration) DeepCopy() *NodeProblemDetectorConfiguration {
	if in == nil {
		return nil
	}
	out := new(NodeProblemDetectorConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSRIOVDevicePluginControllerConfiguration) DeepCopyInto(out *NodeSRIOVDevicePluginControllerConfiguration) {
	*out = *in
	in.BaseComponentConfig.DeepCopyInto(&out.BaseComponentConfig)
	in.BaseControllerConfig.DeepCopyInto(&out.BaseControllerConfig)
	if in.Controller != nil {
		in, out := &in.Controller, &out.Controller
		*out = new(DefaultOverridesConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.DevicePlugin != nil {
		in, out := &in.DevicePlugin, &out.DevicePlugin
		*out = new(NodeSRIOVDevicePluginSettings)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSRIOVDevicePluginControllerConfiguration.
func (in *NodeSRIOVDevicePluginControllerConfiguration) DeepCopy() *NodeSRIOVDevicePluginControllerConfiguration {
	if in == nil {
		return nil
	}
	out := new(NodeSRIOVDevicePluginControllerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSRIOVDevicePluginSettings) DeepCopyInto(out *NodeSRIOVDevicePluginSettings) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.InitImage != nil {
		in, out := &in.InitImage, &out.InitImage
		*out = new(string)
		**out = **in
	}
	if in.DefaultResourcePrefix != nil {
		in, out := &in.DefaultResourcePrefix, &out.DefaultResourcePrefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSRIOVDevicePluginSettings.
func (in *NodeSRIOVDevicePluginSettings) DeepCopy() *NodeSRIOVDevicePluginSettings {
	if in == nil {
		return nil
	}
	out := new(NodeSRIOVDevicePluginSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OVSCNIConfiguration) DeepCopyInto(out *OVSCNIConfiguration) {
	*out = *in
	in.BaseComponentConfig.DeepCopyInto(&out.BaseComponentConfig)
	in.HelmComponentConfig.DeepCopyInto(&out.HelmComponentConfig)
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.CNI != nil {
		in, out := &in.CNI, &out.CNI
		*out = new(DefaultOverridesConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OVSCNIConfiguration.
func (in *OVSCNIConfiguration) DeepCopy() *OVSCNIConfiguration {
	if in == nil {
		return nil
	}
	out := new(OVSCNIConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenTelemetryCollectorConfiguration) DeepCopyInto(out *OpenTelemetryCollectorConfiguration) {
	*out = *in
	in.BaseComponentConfig.DeepCopyInto(&out.BaseComponentConfig)
	in.HelmComponentConfig.DeepCopyInto(&out.HelmComponentConfig)
	if in.Daemon != nil {
		in, out := &in.Daemon, &out.Daemon
		*out = new(DefaultOverridesConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Logging != nil {
		in, out := &in.Logging, &out.Logging
		*out = new(OpenTelemetryCollectorLoggingConfiguration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenTelemetryCollectorConfiguration.
func (in *OpenTelemetryCollectorConfiguration) DeepCopy() *OpenTelemetryCollectorConfiguration {
	if in == nil {
		return nil
	}
	out := new(OpenTelemetryCollectorConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenTelemetryCollectorLoggingConfiguration) DeepCopyInto(out *OpenTelemetryCollectorLoggingConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenTelemetryCollectorLoggingConfiguration.
func (in *OpenTelemetryCollectorLoggingConfiguration) DeepCopy() *OpenTelemetryCollectorLoggingConfiguration {
	if in == nil {
		return nil
	}
	out := new(OpenTelemetryCollectorLoggingConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Overrides) DeepCopyInto(out *Overrides) {
	*out = *in
	if in.Paused != nil {
		in, out := &in.Paused, &out.Paused
		*out = new(bool)
		**out = **in
	}
	if in.DPUCNIBinPath != nil {
		in, out := &in.DPUCNIBinPath, &out.DPUCNIBinPath
		*out = new(string)
		**out = **in
	}
	if in.DPUCNIConfigPath != nil {
		in, out := &in.DPUCNIConfigPath, &out.DPUCNIConfigPath
		*out = new(string)
		**out = **in
	}
	if in.DPUOpenvSwitchRunPath != nil {
		in, out := &in.DPUOpenvSwitchRunPath, &out.DPUOpenvSwitchRunPath
		*out = new(string)
		**out = **in
	}
	if in.DPUOpenvSwitchBinPath != nil {
		in, out := &in.DPUOpenvSwitchBinPath, &out.DPUOpenvSwitchBinPath
		*out = new(string)
		**out = **in
	}
	if in.DPUOpenvSwitchSystemSharedLibPath != nil {
		in, out := &in.DPUOpenvSwitchSystemSharedLibPath, &out.DPUOpenvSwitchSystemSharedLibPath
		*out = new(string)
		**out = **in
	}
	if in.FlannelSkipCNIConfigInstallation != nil {
		in, out := &in.FlannelSkipCNIConfigInstallation, &out.FlannelSkipCNIConfigInstallation
		*out = new(bool)
		**out = **in
	}
	if in.DPUOpenvSwitchSystemSharedLib64Path != nil {
		in, out := &in.DPUOpenvSwitchSystemSharedLib64Path, &out.DPUOpenvSwitchSystemSharedLib64Path
		*out = new(string)
		**out = **in
	}
	if in.DPULinkerCachePath != nil {
		in, out := &in.DPULinkerCachePath, &out.DPULinkerCachePath
		*out = new(string)
		**out = **in
	}
	if in.DPUOptLibraryPath != nil {
		in, out := &in.DPUOptLibraryPath, &out.DPUOptLibraryPath
		*out = new(string)
		**out = **in
	}
	if in.KubernetesAPIServerVIP != nil {
		in, out := &in.KubernetesAPIServerVIP, &out.KubernetesAPIServerVIP
		*out = new(string)
		**out = **in
	}
	if in.KubernetesAPIServerPort != nil {
		in, out := &in.KubernetesAPIServerPort, &out.KubernetesAPIServerPort
		*out = new(int)
		**out = **in
	}
	if in.ArgoCDNamespace != nil {
		in, out := &in.ArgoCDNamespace, &out.ArgoCDNamespace
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Overrides.
func (in *Overrides) DeepCopy() *Overrides {
	if in == nil {
		return nil
	}
	out := new(Overrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisioningControllerConfiguration) DeepCopyInto(out *ProvisioningControllerConfiguration) {
	*out = *in
	in.BaseComponentConfig.DeepCopyInto(&out.BaseComponentConfig)
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.Controller != nil {
		in, out := &in.Controller, &out.Controller
		*out = new(DefaultOverridesConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.BFCFGTemplateConfigMap != nil {
		in, out := &in.BFCFGTemplateConfigMap, &out.BFCFGTemplateConfigMap
		*out = new(string)
		**out = **in
	}
	if in.BFBPersistentVolumeClaimName != nil {
		in, out := &in.BFBPersistentVolumeClaimName, &out.BFBPersistentVolumeClaimName
		*out = new(string)
		**out = **in
	}
	if in.DMSTimeout != nil {
		in, out := &in.DMSTimeout, &out.DMSTimeout
		*out = new(int)
		**out = **in
	}
	if in.CustomCASecretName != nil {
		in, out := &in.CustomCASecretName, &out.CustomCASecretName
		*out = new(string)
		**out = **in
	}
	if in.InstallInterface != nil {
		in, out := &in.InstallInterface, &out.InstallInterface
		*out = new(ProvisioningInstallInterface)
		(*in).DeepCopyInto(*out)
	}
	if in.Registry != nil {
		in, out := &in.Registry, &out.Registry
		*out = new(RegistryConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxDPUParallelInstallations != nil {
		in, out := &in.MaxDPUParallelInstallations, &out.MaxDPUParallelInstallations
		*out = new(int32)
		**out = **in
	}
	if in.MultiDPUOperationsSyncWaitTime != nil {
		in, out := &in.MultiDPUOperationsSyncWaitTime, &out.MultiDPUOperationsSyncWaitTime
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MaxUnavailableDPUNodes != nil {
		in, out := &in.MaxUnavailableDPUNodes, &out.MaxUnavailableDPUNodes
		*out = new(int32)
		**out = **in
	}
	if in.OSInstallTimeout != nil {
		in, out := &in.OSInstallTimeout, &out.OSInstallTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.NodeEffectRemovalTimeout != nil {
		in, out := &in.NodeEffectRemovalTimeout, &out.NodeEffectRemovalTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.HostAgentDNSPolicy != nil {
		in, out := &in.HostAgentDNSPolicy, &out.HostAgentDNSPolicy
		*out = new(corev1.DNSPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisioningControllerConfiguration.
func (in *ProvisioningControllerConfiguration) DeepCopy() *ProvisioningControllerConfiguration {
	if in == nil {
		return nil
	}
	out := new(ProvisioningControllerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisioningInstallInterface) DeepCopyInto(out *ProvisioningInstallInterface) {
	*out = *in
	if in.InstallViaGNOI != nil {
		in, out := &in.InstallViaGNOI, &out.InstallViaGNOI
		*out = new(InstallViaGNOI)
		**out = **in
	}
	if in.InstallViaHostAgent != nil {
		in, out := &in.InstallViaHostAgent, &out.InstallViaHostAgent
		*out = new(InstallViaHostAgent)
		**out = **in
	}
	if in.InstallViaRedfish != nil {
		in, out := &in.InstallViaRedfish, &out.InstallViaRedfish
		*out = new(InstallViaRedfish)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisioningInstallInterface.
func (in *ProvisioningInstallInterface) DeepCopy() *ProvisioningInstallInterface {
	if in == nil {
		return nil
	}
	out := new(ProvisioningInstallInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryConfiguration) DeepCopyInto(out *RegistryConfiguration) {
	*out = *in
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int)
		**out = **in
	}
	if in.LoadBalancerAddress != nil {
		in, out := &in.LoadBalancerAddress, &out.LoadBalancerAddress
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryConfiguration.
func (in *RegistryConfiguration) DeepCopy() *RegistryConfiguration {
	if in == nil {
		return nil
	}
	out := new(RegistryConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceComponentConfig) DeepCopyInto(out *ResourceComponentConfig) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceComponentConfig.
func (in *ResourceComponentConfig) DeepCopy() *ResourceComponentConfig {
	if in == nil {
		return nil
	}
	out := new(ResourceComponentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRequirements) DeepCopyInto(out *ResourceRequirements) {
	*out = *in
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = new(Resources)
		(*in).DeepCopyInto(*out)
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = new(Resources)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRequirements.
func (in *ResourceRequirements) DeepCopy() *ResourceRequirements {
	if in == nil {
		return nil
	}
	out := new(ResourceRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Resources) DeepCopyInto(out *Resources) {
	*out = *in
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Resources.
func (in *Resources) DeepCopy() *Resources {
	if in == nil {
		return nil
	}
	out := new(Resources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SFCControllerConfiguration) DeepCopyInto(out *SFCControllerConfiguration) {
	*out = *in
	in.BaseComponentConfig.DeepCopyInto(&out.BaseComponentConfig)
	in.HelmComponentConfig.DeepCopyInto(&out.HelmComponentConfig)
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.Controller != nil {
		in, out := &in.Controller, &out.Controller
		*out = new(DefaultOverridesConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.SecureFlowDeletionTimeout != nil {
		in, out := &in.SecureFlowDeletionTimeout, &out.SecureFlowDeletionTimeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SFCControllerConfiguration.
func (in *SFCControllerConfiguration) DeepCopy() *SFCControllerConfiguration {
	if in == nil {
		return nil
	}
	out := new(SFCControllerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SRIOVDevicePluginConfiguration) DeepCopyInto(out *SRIOVDevicePluginConfiguration) {
	*out = *in
	in.BaseComponentConfig.DeepCopyInto(&out.BaseComponentConfig)
	in.HelmComponentConfig.DeepCopyInto(&out.HelmComponentConfig)
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.DevicePlugin != nil {
		in, out := &in.DevicePlugin, &out.DevicePlugin
		*out = new(DefaultOverridesConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SRIOVDevicePluginConfiguration.
func (in *SRIOVDevicePluginConfiguration) DeepCopy() *SRIOVDevicePluginConfiguration {
	if in == nil {
		return nil
	}
	out := new(SRIOVDevicePluginConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSetControllerConfiguration) DeepCopyInto(out *ServiceSetControllerConfiguration) {
	*out = *in
	in.BaseComponentConfig.DeepCopyInto(&out.BaseComponentConfig)
	in.BaseControllerConfig.DeepCopyInto(&out.BaseControllerConfig)
	in.HelmComponentConfig.DeepCopyInto(&out.HelmComponentConfig)
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.Controller != nil {
		in, out := &in.Controller, &out.Controller
		*out = new(DefaultOverridesConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSetControllerConfiguration.
func (in *ServiceSetControllerConfiguration) DeepCopy() *ServiceSetControllerConfiguration {
	if in == nil {
		return nil
	}
	out := new(ServiceSetControllerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StaticClusterManagerConfiguration) DeepCopyInto(out *StaticClusterManagerConfiguration) {
	*out = *in
	in.BaseComponentConfig.DeepCopyInto(&out.BaseComponentConfig)
	in.BaseControllerConfig.DeepCopyInto(&out.BaseControllerConfig)
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.Controller != nil {
		in, out := &in.Controller, &out.Controller
		*out = new(DefaultOverridesConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StaticClusterManagerConfiguration.
func (in *StaticClusterManagerConfiguration) DeepCopy() *StaticClusterManagerConfiguration {
	if in == nil {
		return nil
	}
	out := new(StaticClusterManagerConfiguration)
	in.DeepCopyInto(out)
	return out
}
